import type { AppLabels } from './labels.interface';

export const EN_LABELS: AppLabels = {
  navProgram: 'Programme',
  navMyPages: 'My pages',
  navLogout: 'Log out',
  navLogin: 'Log in',
  navOpenMenu: 'Open menu',
  navCloseMenu: 'Close menu',
  navPoweredBy: 'Powered by Conclave',

  programTitle: 'Programme',
  programAllDays: 'All days',
  programResultCount: n => `${n} event${n !== 1 ? 's' : ''}`,
  programSessionsAbbr: 'sess.',
  programNoResults: 'No events match your filter.',

  loginTitle: 'Log in',
  loginEmail: 'Email address',
  loginPassword: 'Password',
  loginButton: 'Log in',
  loginForgotPassword: 'Forgot password?',
  loginNoAccount: 'No account?',
  loginCreateAccount: 'Create an account',

  registerTitle: 'Create account',
  registerName: 'Name',
  registerEmail: 'Email address',
  registerPassword: 'Password',
  registerPasswordHint: 'At least 6 characters',
  registerButton: 'Create account',
  registerSuccessText:
    'Account created! Check your inbox and click the confirmation link to activate your account.',
  registerGoToLogin: 'Go to login',
  registerAlreadyHaveAccount: 'Already have an account?',
  registerLoginLink: 'Log in',

  hubGreeting: name => `Hello, ${name}!`,
  hubTitle: 'My pages',
  hubTicketsTitle: 'My tickets',
  hubTicketsEmpty: 'No tickets yet',
  hubTicketsCta: 'Get tickets →',
  hubEventsTitle: 'My events',
  hubEventsEmpty: 'No events yet',
  hubEventsCta: 'Create event →',
  hubProgramTitle: 'My programme',
  hubProgramEmpty: 'No sessions yet',
  hubProgramCta: 'Browse the programme →',
  hubProgramNext: 'Next:',
  hubProgramSessionCount: n => `${n} registered session${n !== 1 ? 's' : ''}`,
  hubStaffTitle: 'My volunteering',
  hubStaffEmpty: 'No application',
  hubStaffCta: 'Apply as volunteer →',
  hubStaffSubmitted: 'Application submitted',
  hubStaffConfirmed: 'Approved',
  hubStaffAssigned: 'Assigned',
  hubStaffPending: 'Under review',
  hubProfileTitle: 'My profile',
  hubProfileSummary: 'Update contact details and profile information',
  hubProfileCta: 'Open profile →',
  hubBack: '← My pages',

  profileTitle: 'My profile',
  profileWelcomeBanner: 'Welcome! Fill in your name to complete your profile.',
  profileContactSection: 'Contact details',
  profileSavedMessage: 'Profile saved.',
  profileName: 'Name',
  profileEmail: 'Email address',
  profilePhone: 'Phone (optional)',
  profileSaveButton: 'Save',
  profilePasswordSection: 'Change password',
  profilePasswordSaved: 'Password changed.',
  profileCurrentPassword: 'Current password',
  profileNewPassword: 'New password',
  profilePasswordHint: 'At least 6 characters',
  profileConfirmPassword: 'Confirm new password',
  profileChangePasswordButton: 'Change password',

  myEventsTitle: 'My events',
  myEventsNewButton: '+ New event',
  myEventsEmpty: 'You have no events yet.',
  myEventsCreateFirst: 'Create your first event',
  myEventsUnnamed: '(Unnamed event)',
  myEventsSessions: n => `${n} session${n !== 1 ? 's' : ''}`,

  myProgramTitle: 'My programme',
  myProgramTimeline: 'Timeline',
  myProgramShowWatched: 'Show watched',
  myProgramShowPast: 'Show past',
  myProgramNoItems: 'No engagements to show yet.',
  myProgramAllPast: 'All engagements have passed.',
  myProgramShowPastButton: 'Show past',
  myProgramBooked: 'Booked',
  myProgramNoneBooked: 'You have no booked sessions.',
  myProgramVenuePrefix: 'Venue:',
  myProgramCancelling: 'Cancelling...',
  myProgramCancel: 'Cancel',
  myProgramWatched: 'Watched',
  myProgramNoneWatched: 'You are not watching any sessions yet.',
  myProgramBrowse: 'Browse the programme',
  myProgramRemoving: 'Removing...',
  myProgramRemove: 'Remove',
  myProgramUnnamed: '(Unnamed)',
  myProgramPastChip: 'Past',
  myProgramUnnamedSession: '(Unnamed session)',
  myProgramVenueNotSet: 'Not specified',

  forgotTitle: 'Forgot password?',
  forgotDescription: 'Enter your email address and we will send you a link to reset your password.',
  forgotEmail: 'Email address',
  forgotButton: 'Send reset link',
  forgotSuccessText:
    'If the email address is registered, a reset link will be sent shortly. Check your inbox.',
  forgotBackToLogin: 'Back to login',

  resetInvalidTitle: 'Invalid link',
  resetInvalidText: 'The reset link is incomplete. Request a new one via forgot password.',
  resetForgotLink: 'Forgot password?',
  resetSuccessTitle: 'Password reset!',
  resetSuccessText: 'You will be redirected to the login page…',
  resetFormTitle: 'New password',
  resetNewPassword: 'New password',
  resetPasswordHint: 'At least 6 characters',
  resetConfirmPassword: 'Confirm new password',
  resetButton: 'Save new password',

  myStaffTitle: 'My volunteering',
  myStaffApplicationStatus: 'Application status',
  myStaffStatusField: 'Status',
  myStaffShiftsTitle: 'My shifts',
  myStaffNoShifts: 'You have no shifts yet.',
  myStaffApplyTitle: 'Apply as volunteer',
  myStaffRegistrationClosed: 'Volunteer registration is not open for this edition right now.',
  myStaffMotivationLabel: 'Motivation',
  myStaffMotivationPlaceholder: 'Describe how you want to contribute and what experience you have',
  myStaffAreasTitle: 'Staff areas',
  myStaffNoAreas: 'No staff areas have been set up yet.',
  myStaffAvailabilityTitle: 'Availability',
  myStaffNoDates: 'No dates have been set up for this edition.',
  myStaffSubmitting: 'Submitting application...',
  myStaffSubmitButton: 'Submit application',

  myTicketTitle: 'My tickets',
  myTicketRegistrationsTitle: 'Your registrations',
  myTicketTicketLabel: n => `Ticket ${n}`,
  myTicketTypeField: 'Type',
  myTicketReferenceField: 'Reference number',
  myTicketValidDaysField: 'Valid days',
  myTicketCancelling: 'Cancelling...',
  myTicketCancelButton: 'Cancel ticket',
  myTicketPromoLabel: 'Promo code',
  myTicketPromoPlaceholder: 'Enter code',
  myTicketRedeeming: 'Redeeming...',
  myTicketRedeemButton: 'Redeem code',
  myTicketPaymentInfo:
    'Payment is handled separately. Once we register your payment, the status will update automatically.',
  myTicketPaidCancelInfo:
    'Paid tickets with a price above 0 SEK cannot be cancelled. Contact the organiser if you need help.',
  myTicketBookingClosedTitle: 'Ticket booking closed',
  myTicketBookingClosedText: 'Visitor registration is not open for this edition.',
  myTicketSelectTitle: 'Select ticket',
  myTicketNoneAvailable: 'There are no tickets available right now.',
  myTicketVisitorLabel: 'Visitor ticket',
  myTicketLoadingTickets: 'Loading tickets...',
  myTicketTermsLabel: 'I accept the terms of participation.',
  myTicketPaymentNote:
    'Payment is made separately after registration. You will receive payment instructions from the organiser.',
  myTicketBookButton: 'Book ticket',

  eventDetailBreadcrumb: 'Programme',
  eventDetailSessionsTitle: 'Sessions',
  eventDetailNoSessions: 'No sessions scheduled yet.',
  eventDetailSeatsLabel: 'seats',
  eventDetailFixedTime: 'Fixed time',
  eventDetailLoginToRegister: 'Log in to register',
  eventDetailGetTicket: 'Get ticket',
  eventDetailCancelSession: 'Cancel session',
  eventDetailRegisterSession: 'Register for session',
  eventDetailViewInProgram: 'View in My programme',
  eventDetailAboutTitle: 'About the event',
  eventDetailUnknownCategory: 'Unknown category',
  eventDetailWatchAriaLabel: 'Watch session',
  eventDetailUnwatchAriaLabel: 'Remove watch',
  eventDetailLoginForTeam: 'Log in to register team',
  eventDetailRegisterTeam: 'Register team',
  eventDetailCapacityHigh: 'High demand',
  eventDetailCapacityAlmost: 'Filling up',
  eventDetailCapacityGood: 'Plenty of seats',

  confirmLoading: 'Confirming your email address…',
  confirmSuccessTitle: 'Email address confirmed!',
  confirmSuccessText: 'Your account is activated. You can now log in.',
  confirmLoginButton: 'Log in',
  confirmFailTitle: 'Link did not work',
  confirmFailText: 'The confirmation link is invalid or has expired.',
  confirmResentText: 'A new confirmation link has been sent to your email address.',
  confirmResendButton: 'Send new confirmation link',
  confirmBackToLogin: 'Back to login',
};
