import type { AppLabels } from './labels.interface';

export const SV_LABELS: AppLabels = {
  navProgram: 'Program',
  navMyPages: 'Mina sidor',
  navLogout: 'Logga ut',
  navLogin: 'Logga in',
  navOpenMenu: 'Öppna meny',
  navCloseMenu: 'Stäng meny',
  navPoweredBy: 'Powered by Conclave',

  programTitle: 'Program',
  programAllDays: 'Alla dagar',
  programResultCount: n => `${n} evenemang`,
  programSessionsAbbr: 'sess.',
  programNoResults: 'Inga evenemang matchar ditt filter.',

  loginTitle: 'Logga in',
  loginEmail: 'E-postadress',
  loginPassword: 'Lösenord',
  loginButton: 'Logga in',
  loginForgotPassword: 'Glömt lösenordet?',
  loginNoAccount: 'Inget konto?',
  loginCreateAccount: 'Skapa ett konto',

  registerTitle: 'Skapa konto',
  registerName: 'Namn',
  registerEmail: 'E-postadress',
  registerPassword: 'Lösenord',
  registerPasswordHint: 'Minst 6 tecken',
  registerButton: 'Skapa konto',
  registerSuccessText:
    'Konto skapat! Kontrollera din inkorg och klicka på bekräftelselänken för att aktivera ditt konto.',
  registerGoToLogin: 'Gå till inloggning',
  registerAlreadyHaveAccount: 'Har du redan ett konto?',
  registerLoginLink: 'Logga in',

  hubGreeting: name => `Hej, ${name}!`,
  hubTitle: 'Mina sidor',
  hubTicketsTitle: 'Mina biljetter',
  hubTicketsEmpty: 'Inga biljetter ännu',
  hubTicketsCta: 'Skaffa biljetter →',
  hubEventsTitle: 'Mina arrangemang',
  hubEventsEmpty: 'Inga arrangemang ännu',
  hubEventsCta: 'Skapa arrangemang →',
  hubTicketCount: n => `${n} biljett${n !== 1 ? 'er' : ''}`,
  hubLatestConfirmed: 'Senaste bekräftad',
  hubLatestReserved: 'Senaste reserverad',
  hubLatestPricePrefix: 'Senaste pris:',
  hubTotalPricePrefix: 'Totalt:',
  hubPriceNotSpecified: 'Ej angivet',
  hubEventCount: n => `${n} arrangemang`,
  hubPendingCommentCount: n => `${n} obehandlad${n > 1 ? 'e' : ''} kommentar`,
  hubProgramTitle: 'Mitt program',
  hubProgramEmpty: 'Inga sessioner ännu',
  hubProgramCta: 'Bläddra i programmet →',
  hubProgramNext: 'Nästa:',
  hubProgramSessionCount: n => `${n} anmälda sessioner`,
  hubStaffTitle: 'Min funktionering',
  hubStaffEmpty: 'Ingen ansökan',
  hubStaffCta: 'Ansök som funktionär →',
  hubStaffSubmitted: 'Ansökan inskickad',
  hubStaffConfirmed: 'Godkänd',
  hubStaffAssigned: 'Tilldelad',
  hubStaffPending: 'Under behandling',
  hubProfileTitle: 'Min profil',
  hubProfileSummary: 'Uppdatera kontaktuppgifter och profilinformation',
  hubProfileCta: 'Öppna profil →',
  hubBack: '← Mina sidor',

  profileTitle: 'Min profil',
  profileWelcomeBanner: 'Välkommen! Fyll i ditt namn för att slutföra din profil.',
  profileContactSection: 'Kontaktuppgifter',
  profileSavedMessage: 'Profilen sparad.',
  profileName: 'Namn',
  profileEmail: 'E-postadress',
  profilePhone: 'Telefon (valfritt)',
  profileSaveButton: 'Spara',
  profilePasswordSection: 'Byt lösenord',
  profilePasswordSaved: 'Lösenordet är bytt.',
  profileCurrentPassword: 'Nuvarande lösenord',
  profileNewPassword: 'Nytt lösenord',
  profilePasswordHint: 'Minst 6 tecken',
  profileConfirmPassword: 'Bekräfta nytt lösenord',
  profileChangePasswordButton: 'Byt lösenord',

  myEventsTitle: 'Mina arrangemang',
  myEventsNewButton: '+ Nytt arrangemang',
  myEventsEmpty: 'Du har inga arrangemang ännu.',
  myEventsCreateFirst: 'Skapa ditt första arrangemang',
  myEventsUnnamed: '(Namnlöst arrangemang)',
  myEventsSessions: n => `${n} session${n !== 1 ? 'er' : ''}`,
  myEventsUnknownCategory: '—',
  myEventsStatusDraft: 'Utkast',
  myEventsStatusUnderReview: 'Under granskning',
  myEventsStatusPublished: 'Publicerat',
  myEventsStatusCancelled: 'Inställt',

  myProgramTitle: 'Mitt program',
  myProgramTimeline: 'Tidslinje',
  myProgramShowWatched: 'Visa bevakade',
  myProgramShowPast: 'Visa passerade',
  myProgramNoItems: 'Inga engagemang att visa ännu.',
  myProgramAllPast: 'Alla engagemang har passerat.',
  myProgramShowPastButton: 'Visa passerade',
  myProgramBooked: 'Bokade',
  myProgramNoneBooked: 'Du har inga bokade sessioner.',
  myProgramVenuePrefix: 'Lokal:',
  myProgramCancelling: 'Avbokar...',
  myProgramCancel: 'Avboka',
  myProgramWatched: 'Bevakade',
  myProgramNoneWatched: 'Du bevakar inga sessioner ännu.',
  myProgramBrowse: 'Bläddra i programmet',
  myProgramRemoving: 'Tar bort...',
  myProgramRemove: 'Ta bort',
  myProgramUnnamed: '(Namnlös)',
  myProgramPastChip: 'Passerad',
  myProgramUnnamedSession: '(Namnlös programpunkt)',
  myProgramVenueNotSet: 'Ej angiven',
  myProgramScheduleBooked: 'Bokat',
  myProgramScheduleWatching: 'Vill se',
  myProgramScheduleOrganiser: 'Arrangör',
  myProgramScheduleShift: 'Pass',
  myProgramShiftRoleResponsible: 'Ansvarig',
  myProgramShiftRoleAssigned: 'Tilldelad',
  myProgramCancelError: 'Kunde inte avboka sessionen just nu. Försök igen.',
  myProgramRemoveWatchError: 'Kunde inte ta bort bevakningen just nu. Försök igen.',
  myProgramUnknownTime: 'Okänd tid',
  myProgramUnknownDay: 'Okänd dag',

  forgotTitle: 'Glömt lösenordet?',
  forgotDescription:
    'Ange din e-postadress så skickar vi en länk för att återställa lösenordet.',
  forgotEmail: 'E-postadress',
  forgotButton: 'Skicka återställningslänk',
  forgotSuccessText:
    'Om e-postadressen finns registrerad skickas en återställningslänk inom kort. Kontrollera din inkorg.',
  forgotBackToLogin: 'Tillbaka till inloggning',

  resetInvalidTitle: 'Ogiltig länk',
  resetInvalidText: 'Återställningslänken är ofullständig. Begär en ny via glömt lösenord.',
  resetForgotLink: 'Glömt lösenordet?',
  resetSuccessTitle: 'Lösenordet är återställt!',
  resetSuccessText: 'Du omdirigeras till inloggningssidan…',
  resetFormTitle: 'Nytt lösenord',
  resetNewPassword: 'Nytt lösenord',
  resetPasswordHint: 'Minst 6 tecken',
  resetConfirmPassword: 'Bekräfta nytt lösenord',
  resetButton: 'Spara nytt lösenord',
  resetPasswordMismatchError: 'Lösenorden matchar inte.',
  resetInvalidLinkError: 'Länken är ogiltig eller har gått ut.',

  myStaffTitle: 'Min funktionering',
  myStaffApplicationStatus: 'Ansökningsstatus',
  myStaffStatusField: 'Status',
  myStaffShiftsTitle: 'Mina pass',
  myStaffNoShifts: 'Du har inga pass ännu.',
  myStaffApplyTitle: 'Ansök som funktionär',
  myStaffRegistrationClosed:
    'Funktionärsregistrering är inte öppen för denna upplaga just nu.',
  myStaffMotivationLabel: 'Motivering',
  myStaffMotivationPlaceholder: 'Beskriv hur du vill bidra och vad du har erfarenhet av',
  myStaffAreasTitle: 'Staffområden',
  myStaffNoAreas: 'Inga staffområden är upplagda ännu.',
  myStaffAvailabilityTitle: 'Tillgänglighet',
  myStaffNoDates: 'Inga datum finns upplagda för denna upplaga.',
  myStaffSubmitting: 'Skickar ansökan...',
  myStaffSubmitButton: 'Skicka ansökan',
  myStaffUnknownTime: 'Okänd tid',
  myStaffShiftRoleResponsible: 'Ansvarig',
  myStaffShiftRoleAssigned: 'Tilldelad',

  myTicketTitle: 'Mina biljetter',
  myTicketRegistrationsTitle: 'Dina registreringar',
  myTicketTicketLabel: n => `Biljett ${n}`,
  myTicketTypeField: 'Typ',
  myTicketReferenceField: 'Referensnummer',
  myTicketValidDaysField: 'Giltiga dagar',
  myTicketCancelling: 'Avbokar...',
  myTicketCancelButton: 'Avboka biljett',
  myTicketPromoLabel: 'Kampanjkod',
  myTicketPromoPlaceholder: 'Ange kod',
  myTicketRedeeming: 'Löser in...',
  myTicketRedeemButton: 'Lös in kod',
  myTicketPaymentInfo:
    'Betalning hanteras separat. När vi har registrerat din betalning uppdateras statusen automatiskt.',
  myTicketPaidCancelInfo:
    'Betalda biljetter med pris över 0 kr kan inte avbokas. Kontakta arrangören om du behöver hjälp.',
  myTicketBookingClosedTitle: 'Biljettbokning stängd',
  myTicketBookingClosedText: 'Besöksregistrering är inte öppen för denna upplaga.',
  myTicketSelectTitle: 'Välj biljett',
  myTicketNoneAvailable: 'Det finns inga valbara biljetter just nu.',
  myTicketVisitorLabel: 'Besökarbiljett',
  myTicketLoadingTickets: 'Laddar biljetter...',
  myTicketTermsLabel: 'Jag godkänner villkoren för deltagande.',
  myTicketPaymentNote:
    'Betalning sker separat efter registrering. Du får betalningsinstruktioner via arrangören.',
  myTicketBookButton: 'Boka biljett',
  myTicketStatusPendingPayment: 'Inväntar betalning',
  myTicketStatusConfirmed: 'Bekräftad',
  myTicketStatusCancelled: 'Avbokad',
  myTicketStatusPaid: 'Betald',
  myTicketStatusCollected: 'Uthämtad',
  myTicketCategoryOrganiser: 'Arrangörsbiljett',
  myTicketCategoryStaff: 'Funktionärsbiljett',
  myTicketCategoryVisitor: 'Besökarbiljett',
  myTicketDefaultTypeLabel: 'Biljett',
  myTicketPriceMissing: 'Pris saknas',

  eventDetailBreadcrumb: 'Program',
  eventDetailSessionsTitle: 'Sessioner',
  eventDetailNoSessions: 'Inga sessioner schemalagda ännu.',
  eventDetailSeatsLabel: 'platser',
  eventDetailFixedTime: 'Fast tid',
  eventDetailLoginToRegister: 'Logga in för att anmäla',
  eventDetailGetTicket: 'Skaffa biljett',
  eventDetailCancelSession: 'Avboka session',
  eventDetailRegisterSession: 'Anmäl till session',
  eventDetailViewInProgram: 'Visa i Mitt program',
  eventDetailAboutTitle: 'Om evenemanget',
  eventDetailUnknownCategory: 'Okänd kategori',
  eventDetailWatchAriaLabel: 'Bevaka session',
  eventDetailUnwatchAriaLabel: 'Ta bort bevakning',
  eventDetailLoginForTeam: 'Logga in för att anmäla lag',
  eventDetailRegisterTeam: 'Anmäl lag',
  eventDetailCapacityHigh: 'Hög beläggning',
  eventDetailCapacityAlmost: 'Börjar bli fullt',
  eventDetailCapacityGood: 'Gott om plats',
  eventDetailNotFound: 'Evenemanget hittades inte.',
  eventDetailTicketRequired: 'Du behöver en betald biljett innan du kan anmäla dig till en session.',
  eventDetailRegisterError: 'Kunde inte anmäla dig till sessionen just nu.',
  eventDetailCancelError: 'Kunde inte avboka sessionen just nu.',
  eventDetailWatchError: 'Kunde inte bevaka sessionen just nu.',
  eventDetailUnwatchError: 'Kunde inte ta bort bevakningen just nu.',

  publicPageNotFound: 'Sidan hittades inte.',
  publicPageBackHome: 'Till startsidan',

  registerFailedError: 'Registreringen misslyckades. Försök igen.',

  confirmLoading: 'Bekräftar din e-postadress…',
  confirmSuccessTitle: 'E-postadressen bekräftad!',
  confirmSuccessText: 'Ditt konto är aktiverat. Du kan nu logga in.',
  confirmLoginButton: 'Logga in',
  confirmFailTitle: 'Länken fungerade inte',
  confirmFailText: 'Bekräftelselänken är ogiltig eller har gått ut.',
  confirmResentText: 'En ny bekräftelselänk har skickats till din e-postadress.',
  confirmResendButton: 'Skicka ny bekräftelselänk',
  confirmBackToLogin: 'Tillbaka till inloggning',
};
