// <auto-generated />
using ConventionSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ConventionSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ConventionDbContext))]
    [Migration("20260424120000_UseStaffAreaPreferences")]
    partial class UseStaffAreaPreferences
    {
    }
}
