// <auto-generated />
using System;
using ConventionSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConventionSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ConventionDbContext))]
    [Migration("20260413145508_RemoveDefaultValueSqlFromAppGeneratedIds")]
    partial class RemoveDefaultValueSqlFromAppGeneratedIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Aggregates.Convention", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveEditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("active_edition_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("conventions", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Aggregates.Edition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConventionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("convention_id");

                    b.Property<Guid?>("EventCoordinatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_coordinator_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("OrganiserRegistrationOpen")
                        .HasColumnType("bit")
                        .HasColumnName("organiser_registration_open");

                    b.Property<Guid?>("StaffCoordinatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("staff_coordinator_id");

                    b.Property<bool>("StaffRegistrationOpen")
                        .HasColumnType("bit")
                        .HasColumnName("staff_registration_open");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("VisitorRegistrationOpen")
                        .HasColumnType("bit")
                        .HasColumnName("visitor_registration_open");

                    b.HasKey("Id");

                    b.HasIndex("ConventionId")
                        .HasDatabaseName("IX_editions_convention_id");

                    b.ToTable("editions", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("responsible_id");

                    b.HasKey("Id");

                    b.HasIndex("EditionId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.ConventionAdministrator", b =>
                {
                    b.Property<Guid>("ConventionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("added_at");

                    b.Property<Guid>("AddedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("added_by_id");

                    b.HasKey("ConventionId", "PersonId");

                    b.ToTable("convention_administrators", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConventionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("convention_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ConventionId", "Email")
                        .HasDatabaseName("IX_persons_convention_id_email");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.StaffArea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("responsible_id");

                    b.HasKey("Id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_staff_areas_edition_id");

                    b.ToTable("staff_areas", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("StaffAreaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("staff_area_id");

                    b.HasKey("Id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_stations_edition_id");

                    b.HasIndex("StaffAreaId")
                        .HasDatabaseName("IX_stations_staff_area_id");

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EditionId");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Aggregates.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DropInRules")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("drop_in_rules");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("edition_id");

                    b.Property<Guid>("LeadOrganiserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lead_organiser_id");

                    b.Property<string>("RegistrationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("registration_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_events_category_id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_events_edition_id");

                    b.HasIndex("LeadOrganiserId")
                        .HasDatabaseName("IX_events_lead_organiser_id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.CoOrganiser", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("added_at");

                    b.HasKey("EventId", "PersonId");

                    b.ToTable("co_organisers", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.EventComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("event_comments", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("int")
                        .HasColumnName("max_seats");

                    b.Property<string>("StartType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("start_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_sessions_event_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("IX_sessions_venue_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.SessionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RequestedDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("requested_duration_minutes");

                    b.Property<int>("RequestedSeats")
                        .HasColumnType("int")
                        .HasColumnName("requested_seats");

                    b.Property<string>("StartType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("start_type");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_session_requests_event_id");

                    b.ToTable("session_requests", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Aggregates.SessionRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_session_registrations_person_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_session_registrations_session_id");

                    b.ToTable("session_registrations", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Aggregates.StaffApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("edition_id");

                    b.Property<string>("InterestDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("interest_description");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_staff_applications_edition_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_staff_applications_person_id");

                    b.ToTable("staff_applications", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Aggregates.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_by_id");

                    b.Property<DateTimeOffset?>("CollectedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("collected_at");

                    b.Property<Guid?>("CollectedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("collected_by_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("edition_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TicketTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_type_id");

                    b.HasKey("Id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_tickets_edition_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_tickets_person_id");

                    b.HasIndex("TicketTypeId")
                        .HasDatabaseName("IX_tickets_ticket_type_id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Aggregates.VisitorRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("edition_id");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("payment_reference");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_visitor_registrations_edition_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_visitor_registrations_person_id");

                    b.ToTable("visitor_registrations", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Entities.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StaffApplicationId");

                    b.ToTable("staff_application_availabilities", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Entities.TicketPerk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TicketTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("ticket_perks", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Entities.TicketType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("edition_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_ticket_types_edition_id");

                    b.ToTable("ticket_types", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Staff.Aggregates.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("responsible_id");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("station_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .HasDatabaseName("IX_shifts_station_id");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Staff.Entities.StaffAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_by_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("staff_assignments", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Infrastructure.Persistence.DomainEventLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("domain_event_log", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Aggregates.Edition", b =>
                {
                    b.OwnsOne("ConventionSystem.Domain.Convention.ValueObjects.DatePeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("EditionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");

                            b1.HasKey("EditionId");

                            b1.ToTable("editions");

                            b1.WithOwner()
                                .HasForeignKey("EditionId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.Category", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Convention.Aggregates.Edition", null)
                        .WithMany("Categories")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.ConventionAdministrator", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Convention.Aggregates.Convention", null)
                        .WithMany("Administrators")
                        .HasForeignKey("ConventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.StaffArea", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Convention.Aggregates.Edition", null)
                        .WithMany("StaffAreas")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.Station", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Convention.Aggregates.Edition", null)
                        .WithMany("Stations")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.Venue", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Convention.Aggregates.Edition", null)
                        .WithMany("Venues")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.CoOrganiser", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Event.Aggregates.Event", null)
                        .WithMany("CoOrganisers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.EventComment", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Event.Aggregates.Event", null)
                        .WithMany("Comments")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.Session", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Event.Aggregates.Event", null)
                        .WithMany("Sessions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ConventionSystem.Domain.Event.ValueObjects.TimeSlot", "TimeSlot", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("End")
                                .HasColumnType("datetime2")
                                .HasColumnName("end_time");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("datetime2")
                                .HasColumnName("start_time");

                            b1.HasKey("SessionId");

                            b1.ToTable("sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("TimeSlot")
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.SessionRequest", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Event.Aggregates.Event", null)
                        .WithMany("SessionRequests")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Aggregates.StaffApplication", b =>
                {
                    b.OwnsMany("ConventionSystem.Domain.Registration.Entities.StationPreference", "StationPreferences", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasDefaultValueSql("newsequentialid()");

                            b1.Property<Guid>("StaffApplicationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("StationId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("station_id");

                            b1.HasKey("Id");

                            b1.HasIndex("StaffApplicationId");

                            b1.ToTable("staff_application_stations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StaffApplicationId");
                        });

                    b.Navigation("StationPreferences");
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Entities.Availability", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Registration.Aggregates.StaffApplication", null)
                        .WithMany("Availabilities")
                        .HasForeignKey("StaffApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ConventionSystem.Domain.Registration.ValueObjects.TimeSlot", "TimeSlot", b1 =>
                        {
                            b1.Property<Guid>("AvailabilityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("End")
                                .HasColumnType("datetime2")
                                .HasColumnName("end");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("datetime2")
                                .HasColumnName("start");

                            b1.HasKey("AvailabilityId");

                            b1.ToTable("staff_application_availabilities");

                            b1.WithOwner()
                                .HasForeignKey("AvailabilityId");
                        });

                    b.Navigation("TimeSlot")
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Entities.TicketPerk", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Registration.Entities.TicketType", null)
                        .WithMany("Perks")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Staff.Aggregates.Shift", b =>
                {
                    b.OwnsOne("ConventionSystem.Domain.Staff.ValueObjects.StaffingRequirement", "StaffingRequirement", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("MaxPersons")
                                .HasColumnType("int")
                                .HasColumnName("max_persons");

                            b1.Property<int>("MinPersons")
                                .HasColumnType("int")
                                .HasColumnName("min_persons");

                            b1.HasKey("ShiftId");

                            b1.ToTable("shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsOne("ConventionSystem.Domain.Staff.ValueObjects.TimeSlot", "TimeSlot", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("End")
                                .HasColumnType("datetime2")
                                .HasColumnName("end_time");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("datetime2")
                                .HasColumnName("start_time");

                            b1.HasKey("ShiftId");

                            b1.ToTable("shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.Navigation("StaffingRequirement")
                        .IsRequired();

                    b.Navigation("TimeSlot")
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Staff.Entities.StaffAssignment", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Staff.Aggregates.Shift", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Aggregates.Convention", b =>
                {
                    b.Navigation("Administrators");
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Aggregates.Edition", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("StaffAreas");

                    b.Navigation("Stations");

                    b.Navigation("Venues");
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Aggregates.Event", b =>
                {
                    b.Navigation("CoOrganisers");

                    b.Navigation("Comments");

                    b.Navigation("SessionRequests");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Aggregates.StaffApplication", b =>
                {
                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Entities.TicketType", b =>
                {
                    b.Navigation("Perks");
                });

            modelBuilder.Entity("ConventionSystem.Domain.Staff.Aggregates.Shift", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
