// <auto-generated />
using System;
using ConventionSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConventionSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ConventionDbContext))]
    partial class ConventionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConventionSystem.Domain.Content.Aggregates.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasMaxLength(20000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<Guid>("ConventionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("convention_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("edition_id");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit")
                        .HasColumnName("is_published");

                    b.Property<int>("MenuSortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("menu_sort_order");

                    b.Property<bool>("ShowInPublicMenu")
                        .HasColumnType("bit")
                        .HasColumnName("show_in_public_menu");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ConventionId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_pages_convention_id_slug")
                        .HasFilter("[edition_id] IS NULL");

                    b.HasIndex("ConventionId", "EditionId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_pages_convention_id_edition_id_slug")
                        .HasFilter("[edition_id] IS NOT NULL");

                    b.ToTable("pages", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Aggregates.Convention", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveEditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("active_edition_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("conventions", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Aggregates.Edition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConventionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("convention_id");

                    b.Property<Guid?>("EventCoordinatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_coordinator_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("OrganiserRegistrationOpen")
                        .HasColumnType("bit")
                        .HasColumnName("organiser_registration_open");

                    b.Property<Guid?>("StaffCoordinatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("staff_coordinator_id");

                    b.Property<bool>("StaffRegistrationOpen")
                        .HasColumnType("bit")
                        .HasColumnName("staff_registration_open");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("VisitorRegistrationOpen")
                        .HasColumnType("bit")
                        .HasColumnName("visitor_registration_open");

                    b.HasKey("Id");

                    b.HasIndex("ConventionId")
                        .HasDatabaseName("IX_editions_convention_id");

                    b.HasIndex("TenantId");

                    b.ToTable("editions", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrganizerInstructions")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("organizer_instructions");

                    b.Property<string>("PublicDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("public_description");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("responsible_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("EditionId");

                    b.HasIndex("TenantId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.ConventionAdministrator", b =>
                {
                    b.Property<Guid>("ConventionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("added_at");

                    b.Property<Guid>("AddedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("added_by_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("ConventionId", "PersonId");

                    b.HasIndex("TenantId");

                    b.ToTable("convention_administrators", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.ConventionBranding", b =>
                {
                    b.Property<Guid>("ConventionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("convention_id");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("accent_color");

                    b.Property<string>("CustomCss")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("custom_css");

                    b.Property<string>("FaviconUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("favicon_url");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("font_family");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("logo_url");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("primary_color");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("ConventionId");

                    b.HasIndex("TenantId");

                    b.ToTable("convention_brandings", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.EditionContent", b =>
                {
                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("edition_id");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("value");

                    b.HasKey("EditionId", "Key");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_edition_content_edition_id");

                    b.HasIndex("TenantId");

                    b.ToTable("edition_content", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.EditionScheduleDay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("EditionId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_edition_schedule_days_edition_id_date");

                    b.ToTable("edition_schedule_days", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConventionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("convention_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ConventionId", "Email")
                        .HasDatabaseName("IX_persons_convention_id_email");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.ReceptionStaff", b =>
                {
                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("edition_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("added_at");

                    b.Property<Guid>("AddedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("added_by_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("EditionId", "PersonId");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_edition_reception_staff_edition_id");

                    b.HasIndex("TenantId");

                    b.ToTable("edition_reception_staff", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.StaffArea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("responsible_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_staff_areas_edition_id");

                    b.HasIndex("TenantId");

                    b.ToTable("staff_areas", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("StaffAreaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("staff_area_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_stations_edition_id");

                    b.HasIndex("StaffAreaId")
                        .HasDatabaseName("IX_stations_staff_area_id");

                    b.HasIndex("TenantId");

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("EditionId");

                    b.HasIndex("TenantId");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Aggregates.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<int>("CoOrganiserCount")
                        .HasColumnType("int")
                        .HasColumnName("co_organiser_count");

                    b.Property<int>("CoOrganiserLimit")
                        .HasColumnType("int")
                        .HasColumnName("co_organiser_limit");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DropInRules")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("drop_in_rules");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("edition_id");

                    b.Property<int?>("FeaturedSortOrder")
                        .HasColumnType("int")
                        .HasColumnName("featured_sort_order");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<Guid>("LeadOrganiserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lead_organiser_id");

                    b.Property<string>("RegistrationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("registration_type");

                    b.Property<string>("ScheduleRequestText")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("schedule_request_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_events_category_id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_events_edition_id");

                    b.HasIndex("LeadOrganiserId")
                        .HasDatabaseName("IX_events_lead_organiser_id");

                    b.HasIndex("TenantId");

                    b.HasIndex("EditionId", "IsFeatured")
                        .HasDatabaseName("IX_events_edition_id_is_featured");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.CoOrganiser", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("added_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("EventId", "PersonId");

                    b.HasIndex("TenantId");

                    b.ToTable("co_organisers", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.CoOrganiserInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("normalized_email");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_co_organiser_invitations_code");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_co_organiser_invitations_event_id");

                    b.HasIndex("TenantId");

                    b.ToTable("co_organiser_invitations", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.EventComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("acknowledged_by_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("HandledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("handled_at");

                    b.Property<Guid?>("HandledById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("handled_by_id");

                    b.Property<string>("HandlingComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("handling_comment");

                    b.Property<bool>("RequiresHandling")
                        .HasColumnType("bit")
                        .HasColumnName("requires_handling");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TenantId");

                    b.ToTable("event_comments", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("int")
                        .HasColumnName("max_seats");

                    b.Property<string>("StartType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("start_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_sessions_event_id");

                    b.HasIndex("TenantId");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("IX_sessions_venue_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Aggregates.PromotionCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowedTicketTypeIds")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("allowed_ticket_type_ids");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("discount_type");

                    b.Property<int>("DiscountValue")
                        .HasColumnType("int")
                        .HasColumnName("discount_value");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("edition_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxRedemptions")
                        .HasColumnType("int")
                        .HasColumnName("max_redemptions");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("EditionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_promotion_codes_edition_id_code");

                    b.ToTable("promotion_codes", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Aggregates.SessionRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_session_registrations_person_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_session_registrations_session_id");

                    b.HasIndex("TenantId");

                    b.ToTable("session_registrations", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Aggregates.SessionWatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("edition_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_session_watches_edition_id");

                    b.HasIndex("TenantId");

                    b.HasIndex("PersonId", "SessionId")
                        .IsUnique()
                        .HasDatabaseName("IX_session_watches_person_session_unique");

                    b.ToTable("session_watches", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Aggregates.StaffApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("edition_id");

                    b.Property<string>("InterestDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("interest_description");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_staff_applications_edition_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_staff_applications_person_id");

                    b.HasIndex("TenantId");

                    b.ToTable("staff_applications", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Aggregates.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_by_id");

                    b.Property<DateTimeOffset?>("CollectedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("collected_at");

                    b.Property<Guid?>("CollectedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("collected_by_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("edition_id");

                    b.Property<int?>("FinalPrice")
                        .HasColumnType("int")
                        .HasColumnName("final_price");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<Guid?>("PromotionCodeRedemptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("promotion_code_redemption_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TicketTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_type_id");

                    b.HasKey("Id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_tickets_edition_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_tickets_person_id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TicketTypeId")
                        .HasDatabaseName("IX_tickets_ticket_type_id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Aggregates.VisitorRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("edition_id");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("payment_reference");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_visitor_registrations_edition_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_visitor_registrations_person_id");

                    b.HasIndex("TenantId");

                    b.ToTable("visitor_registrations", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Entities.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("StaffApplicationId");

                    b.HasIndex("TenantId");

                    b.ToTable("staff_application_availabilities", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Entities.PromotionCodeRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DiscountApplied")
                        .HasColumnType("int")
                        .HasColumnName("discount_applied");

                    b.Property<int>("FinalPrice")
                        .HasColumnType("int")
                        .HasColumnName("final_price");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<Guid>("PromotionCodeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("promotion_code_id");

                    b.Property<DateTimeOffset>("RedeemedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("redeemed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("TicketTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_type_id");

                    b.HasKey("Id");

                    b.HasIndex("PromotionCodeId")
                        .HasDatabaseName("IX_promotion_code_redemptions_promotion_code_id");

                    b.HasIndex("TenantId");

                    b.ToTable("promotion_code_redemptions", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Entities.TicketType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowedCategories")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("allowed_categories");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("edition_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ValidDays")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valid_days");

                    b.HasKey("Id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("IX_ticket_types_edition_id");

                    b.HasIndex("TenantId");

                    b.ToTable("ticket_types", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Staff.Aggregates.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("responsible_id");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("station_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .HasDatabaseName("IX_shifts_station_id");

                    b.HasIndex("TenantId");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Staff.Entities.StaffAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_by_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("person_id");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TenantId");

                    b.ToTable("staff_assignments", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Tenancy.Aggregates.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.HasKey("Id");

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Infrastructure.Persistence.DomainEventLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_domain_event_log_occurred_at");

                    b.ToTable("domain_event_log", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ProcessAfter")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("process_after");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Aggregates.Edition", b =>
                {
                    b.OwnsOne("ConventionSystem.Domain.Convention.ValueObjects.DatePeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("EditionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");

                            b1.HasKey("EditionId");

                            b1.ToTable("editions");

                            b1.WithOwner()
                                .HasForeignKey("EditionId");
                        });

                    b.OwnsMany("ConventionSystem.Domain.Convention.ValueObjects.ProgramTagDefinition", "ProgramTagDefinitions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasDefaultValueSql("newsequentialid()");

                            b1.Property<Guid>("EditionId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("edition_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("name");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("tenant_id");

                            b1.HasKey("Id");

                            b1.HasIndex("TenantId")
                                .HasDatabaseName("IX_edition_program_tag_definitions_tenant_id");

                            b1.HasIndex("EditionId", "Name")
                                .IsUnique()
                                .HasDatabaseName("IX_edition_program_tag_definitions_edition_id_name");

                            b1.ToTable("edition_program_tag_definitions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EditionId");
                        });

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("ProgramTagDefinitions");
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.Category", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Convention.Aggregates.Edition", null)
                        .WithMany("Categories")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.ConventionAdministrator", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Convention.Aggregates.Convention", null)
                        .WithMany("Administrators")
                        .HasForeignKey("ConventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.ConventionBranding", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Convention.Aggregates.Convention", null)
                        .WithOne()
                        .HasForeignKey("ConventionSystem.Domain.Convention.Entities.ConventionBranding", "ConventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.EditionContent", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Convention.Aggregates.Edition", null)
                        .WithMany("Content")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.EditionScheduleDay", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Convention.Aggregates.Edition", null)
                        .WithMany("ScheduleDays")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.ReceptionStaff", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Convention.Aggregates.Edition", null)
                        .WithMany("ReceptionStaff")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.StaffArea", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Convention.Aggregates.Edition", null)
                        .WithMany("StaffAreas")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.Station", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Convention.Aggregates.Edition", null)
                        .WithMany("Stations")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Entities.Venue", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Convention.Aggregates.Edition", null)
                        .WithMany("Venues")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Aggregates.Event", b =>
                {
                    b.OwnsMany("ConventionSystem.Domain.Event.ValueObjects.EventProgramTag", "ProgramTags", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasDefaultValueSql("newsequentialid()");

                            b1.Property<Guid>("EventId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("event_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("name");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("tenant_id");

                            b1.HasKey("Id");

                            b1.HasIndex("TenantId")
                                .HasDatabaseName("IX_event_program_tags_tenant_id");

                            b1.HasIndex("EventId", "Name")
                                .IsUnique()
                                .HasDatabaseName("IX_event_program_tags_event_id_name");

                            b1.ToTable("event_program_tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("ProgramTags");
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.CoOrganiser", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Event.Aggregates.Event", null)
                        .WithMany("CoOrganisers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.CoOrganiserInvitation", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Event.Aggregates.Event", null)
                        .WithMany("CoOrganiserInvitations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.EventComment", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Event.Aggregates.Event", null)
                        .WithMany("Comments")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Entities.Session", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Event.Aggregates.Event", null)
                        .WithMany("Sessions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ConventionSystem.Domain.Event.ValueObjects.TimeSlot", "TimeSlot", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("End")
                                .HasColumnType("datetime2")
                                .HasColumnName("end_time");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("datetime2")
                                .HasColumnName("start_time");

                            b1.HasKey("SessionId");

                            b1.ToTable("sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("TimeSlot")
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Aggregates.StaffApplication", b =>
                {
                    b.OwnsMany("ConventionSystem.Domain.Registration.Entities.StaffAreaPreference", "StaffAreaPreferences", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasDefaultValueSql("newsequentialid()");

                            b1.Property<Guid>("StaffApplicationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("StaffAreaId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("staff_area_id");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("tenant_id");

                            b1.HasKey("Id");

                            b1.HasIndex("StaffApplicationId");

                            b1.HasIndex("TenantId");

                            b1.ToTable("staff_application_staff_areas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StaffApplicationId");
                        });

                    b.Navigation("StaffAreaPreferences");
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Entities.Availability", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Registration.Aggregates.StaffApplication", null)
                        .WithMany("Availabilities")
                        .HasForeignKey("StaffApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ConventionSystem.Domain.Registration.ValueObjects.TimeSlot", "TimeSlot", b1 =>
                        {
                            b1.Property<Guid>("AvailabilityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("End")
                                .HasColumnType("datetime2")
                                .HasColumnName("end");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("datetime2")
                                .HasColumnName("start");

                            b1.HasKey("AvailabilityId");

                            b1.ToTable("staff_application_availabilities");

                            b1.WithOwner()
                                .HasForeignKey("AvailabilityId");
                        });

                    b.Navigation("TimeSlot")
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Entities.PromotionCodeRedemption", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Registration.Aggregates.PromotionCode", null)
                        .WithMany("Redemptions")
                        .HasForeignKey("PromotionCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Staff.Aggregates.Shift", b =>
                {
                    b.OwnsOne("ConventionSystem.Domain.Staff.ValueObjects.StaffingRequirement", "StaffingRequirement", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("MaxPersons")
                                .HasColumnType("int")
                                .HasColumnName("max_persons");

                            b1.Property<int>("MinPersons")
                                .HasColumnType("int")
                                .HasColumnName("min_persons");

                            b1.HasKey("ShiftId");

                            b1.ToTable("shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsOne("ConventionSystem.Domain.Staff.ValueObjects.TimeSlot", "TimeSlot", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("End")
                                .HasColumnType("datetime2")
                                .HasColumnName("end_time");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("datetime2")
                                .HasColumnName("start_time");

                            b1.HasKey("ShiftId");

                            b1.ToTable("shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.Navigation("StaffingRequirement")
                        .IsRequired();

                    b.Navigation("TimeSlot")
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Staff.Entities.StaffAssignment", b =>
                {
                    b.HasOne("ConventionSystem.Domain.Staff.Aggregates.Shift", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Aggregates.Convention", b =>
                {
                    b.Navigation("Administrators");
                });

            modelBuilder.Entity("ConventionSystem.Domain.Convention.Aggregates.Edition", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Content");

                    b.Navigation("ReceptionStaff");

                    b.Navigation("ScheduleDays");

                    b.Navigation("StaffAreas");

                    b.Navigation("Stations");

                    b.Navigation("Venues");
                });

            modelBuilder.Entity("ConventionSystem.Domain.Event.Aggregates.Event", b =>
                {
                    b.Navigation("CoOrganiserInvitations");

                    b.Navigation("CoOrganisers");

                    b.Navigation("Comments");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Aggregates.PromotionCode", b =>
                {
                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("ConventionSystem.Domain.Registration.Aggregates.StaffApplication", b =>
                {
                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("ConventionSystem.Domain.Staff.Aggregates.Shift", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
