/** Navigationsrubriker och sidenav-etiketter. */
export const NAV = {
  dashboard:      'Dashboard',
  personRegistry: 'Personregister',
  visitors:       'Besökare',
  organisers:     'Arrangörer',
  staff:          'Funktionärer',
  responsibles:   'Ansvariga',
  events:         'Evenemang',
  sessions:       'Schemaläggning',
  staffAreas:     'Funktionsområden',
  staffApplications: 'Ansökningar',
  visitorRegistrations: 'Biljetter',
  promotionCodes: 'Kampanjkoder',
  feeds:          'Feeds',
  logout:         'Logga ut',
  toggleMenu:     'Växla meny',
  showSection:    'Visa sektion',
  hideSection:    'Dölj sektion',
  chooseEdition:  'Välj upplaga',
  activeSuffix:   '· Aktiv',
  editionsSection: 'Upplaga',
  editionBasics:  'Grunduppgifter',
  editionLifecycle: 'Läge',
  editionVenues:  'Lokaler',
  editionCategories: 'Kategorier',
  editionTicketTypes: 'Biljettyper',
  editionExport: 'Export',
  eventsSection:  'Evenemang',
  staffingSection: 'Bemanning',
  visitorsSection: 'Besökare',
  personsSection:  'Personer',
} as const;
