/** Sidspecifika texter: rubriker, felsidor, tomma tillstånd. */

export const EVENT_DETAIL = {
  backLink:                'Evenemang',
  noName:                  '(Inget namn)',
  rejectTitle:             'Avvisa evenemang',
  rejectHint:              'Ange en kommentar som förklarar varför evenemanget avvisas. Arrangören kan se kommentaren.',
  rejectCommentPlaceholder: 'Beskriv vad som behöver ändras…',
  sendRejection:           'Skicka avvisning',
  pendingCommentsTitle:    'Obehandlade kommentarer',
  responseFieldLabel:      'Beskriv vad som justerats',
  noComments:              'Inga obehandlade kommentarer.',
  detailsTab:              'Detaljer',
  scheduleTab:             'Schema',
  coOrganisersTab:         'Medarrangörer',
  titlePlaceholder:        'Evenemangets titel',
  descriptionPlaceholder:  'Beskriv evenemanget…',
  dropInPlaceholder:       'Beskriv hur drop-in fungerar',
  requestsTitle:           'Schemaönskemål',
  requestsEmpty:           'Inga schemaönskemål.',
  requestTextPlaceholder:  'Beskriv önskemål om tid, längd, lokaler eller annat som schemaläggaren behöver veta.',
  sessionsTitle:           'Schemalagda sessioner',
  sessionsEmpty:           'Inga sessioner schemalagda ännu.',
  addSessionAction:        'Schemalägg session',
  timelineTitle:           'Tidslinje',
  // Bekräftelsedialog – ta bort arrangemang
  deleteTitle:             'Ta bort arrangemang',
  deleteMessage:           (title: string) => `Ta bort arrangemanget "${title}" permanent?`,
} as const;

export const EDITION_DETAIL = {
  backLink:          'Dashboard',
  editTitle:         'Redigera grunddata',
  editTooltip:       'Redigera grunddata',
  lifecycleTab:       'Livscykel',
  stateCardTitle:     'Editionslivscykel',
  stateCardHint:      'Underhåll upplagans livscykel: publicera, aktivera och hantera registreringar.',
  publishTitle:       'Publicering',
  publishHint:        'Upplagan måste publiceras innan den kan aktiveras och öppna registreringar.',
  activeEditionTitle: 'Aktiv upplaga',
  activeEditionHint:  'Den aktiva upplagan används som standard i adminvyer och visas publikt.',
  publicationDone:    'Redan publicerad',
  statusActive:       'Aktiv',
  statusNotActive:    'Inte aktiv',
  registrationsTitle: 'Registreringsfönster',
  registrationsHint:  'Öppna och stäng ansöknings- och registreringsperioder.',
  staffLabel:        'Funktionär:',
  eventLabel:        'Evenemang:',
  publishAction:     'Publicera upplaga',
  unpublishAction:   'Avpublicera upplaga',
  setActiveAction:   'Sätt som aktiv',
  visitorRegLabel:   'Besökarregistrering',
  visitorSubLabel:   'Besökarregistrering:',
  alreadyOpen:       'Redan öppen',
  requiresPublished: 'Kräver publicerad upplaga',
  organiserSubLabel: 'Arrangemangsansökan:',
  staffSubLabel:     'Funktionärsansökan:',
  statusOpen:        'Öppen',
  statusDraft:       'Utkast',
  statusPublished:   'Publicerad',
  statusClosed:      'Stängd',
  venuesTitle:       'Lokaler',
  venuesEmpty:       'Inga lokaler tillagda.',
  addVenueTitle:     'Lägg till lokal',
  staffAreasTitle:   'Funktioneringsområden',
  staffAreasEmpty:   'Inga funktioneringsområden tillagda.',
  addStaffAreaTitle: 'Lägg till funktioneringsområde',
  categoriesTitle:   'Kategorier',
  categoriesEmpty:   'Inga kategorier tillagda.',
  addCategoryTitle:  'Lägg till kategori',
  ticketTypesTitle:  'Biljettyper',
  ticketTypesEmpty:  'Inga biljettyper tillagda.',
  addTicketTitle:    'Lägg till biljetttyp',
  fieldBuilding:          'Byggnad',
  fieldPrice:             'Pris (kr)',
  fieldSellable:          'Säljbar',
  fieldPubliclyVisible:   'Synlig publikt',
  // Bekräftelsedialoger
  publishConfirmTitle:    'Publicera upplaga',
  publishConfirmMessage:  'Publicera upplagan nu?',
  unpublishConfirmTitle:  'Avpublicera upplaga',
  unpublishConfirmMessage:'Avpublicera upplagan och stäng alla registreringsfönster?',
  deleteVenueTitle:       'Ta bort lokal',
  deleteVenueMessage:     (name: string) => `Ta bort lokalen "${name}"?`,
  deleteStaffAreaTitle:   'Ta bort funktioneringsområde',
  deleteStaffAreaMessage: (name: string) => `Ta bort funktioneringsområdet "${name}"? Alla tillhörande stationer tas också bort.`,
  deleteCategoryTitle:    'Ta bort kategori',
  deleteCategoryMessage:  (name: string) => `Ta bort kategorin "${name}"?`,
  deleteTicketTypeTitle:   'Ta bort biljetttyp',
  deleteTicketTypeMessage: (name: string) => `Ta bort biljetttypen "${name}"?`,
} as const;

export const SESSION_TIMELINE = {
  empty:          'Inga sessioner schemalagda ännu. Välj lokal och tid i formuläret för att se ett förslag.',
  conflictBanner: 'Tidskonflikten – den pågående sessionen krockar med en annan session i samma lokal.',
  draftTitle:     'Pågår / förslag',
  conflict:       'Konflikt!',
  inProgress:     'Pågår…',
  legendOwn:      'Eget evenemang',
  legendOther:    'Annat evenemang',
  legendDraft:    'Pågår / förslag',
  legendConflict: 'Konflikt',
} as const;

export const SESSIONS_OVERVIEW = {
  title:            'Schemaläggning',
  formTitle:        'Schemalägg session',
  perspectiveVenue: 'Lokalperspektiv',
  perspectiveEvent: 'Arrangemangsperspektiv',
  buildingFilter:   'Byggnad',
  categoryFilter:   'Kategori',
  searchFilter:     'Fritext',
  allOption:        'Alla',
  requestsForEventTitle: 'Schemaönskemål för valt evenemang',
  noRequestsForEvent: 'Det finns inga schemaönskemål för evenemanget.',
  timelineView:    'Tidslinjevy',
  tableView:       'Tabellvy',
  timelineTitleVenue: 'Tidslinje per lokal',
  timelineTitleEvent: 'Tidslinje per arrangemang',
  scheduledTitle:   'Schemalagda sessioner',
  noSessions:       'Inga schemalagda sessioner i aktuellt urval.',
  conflictDetected: 'Konflikt upptäckt: sessionen överlappar annan session i samma lokal.',
  updateSession:    'Uppdatera session',
  deleteSessionTitle: 'Ta bort session',
  deleteSessionMessage: 'Vill du ta bort sessionen? Den inaktiveras och visas inte längre i schemat.',
  eventColumn:      'Evenemang',
  start:            'Start',
  end:              'Slut',
} as const;

export const ERROR_PAGE = {
  '401': {
    code:        '401',
    title:       'Inte inloggad',
    description: 'Du måste logga in för att komma åt den här sidan.',
    action:      'Gå till inloggning',
  },
  '403': {
    code:        '403',
    title:       'Ingen behörighet',
    description: 'Du har inte behörighet att se den här sidan. Adminrättigheter krävs.',
    action:      'Till inloggning',
  },
  '404': {
    code:        '404',
    title:       'Sidan hittades inte',
    description: 'Sidan du letar efter finns inte eller har flyttats.',
    action:      'Tillbaka till start',
  },
} as const;
export const STAFF_TIMELINE = {
  empty:           'Inga funktioneringspass att visa i schemat ännu.',
  areaResponsible: 'Ansvarig',
  staffing:        'Funktionering',
  legendUnstaffed: 'Obemannat',
  legendUnderMin:  'Under min',
  legendWithin:    'Inom behov',
  legendFull:      'Fullbemannat',
  legendOverMax:   'Över max',
  legendCancelled: 'Inställt',
} as const;

export const STAFFING_OVERVIEW = {
  title:            'Funktioneringsschema',
  subtitle:         'Överblick över pass, stationer och funktioneringsläge för den valda upplagan.',
  dayFilter:        'Dag',
  areaFilter:       'Funktionsområde',
  stationFilter:    'Station',
  statusFilter:     'Funktioneringsläge',
  allOption:        'Alla',
  timelineView:     'Tidslinjevy',
  tableView:        'Tabellvy',
  timelineTitle:    'Tidslinje per station',
  tableTitle:       'Pass i urvalet',
  noShifts:         'Inga pass matchar aktuella filter.',
  areaColumn:       'Funktionsområde',
  stationColumn:    'Station',
  startColumn:      'Start',
  endColumn:        'Slut',
  responsibleColumn:'Ansvarig',
  staffingColumn:   'Funktionering',
  statusColumn:     'Läge',
  openAreaAction:   'Öppna område',
  selectedShift:    'Valt pass',
  createShiftAction:'Skapa pass',
  createShiftTitle: 'Nytt pass från schemavyn',
  responsibleField: 'Ansvarig',
  createShiftHint:  'Station och tid är förifyllda från aktuell vy men kan justeras innan du sparar.',
  cancelAction:     'Avbryt',
  cancelShiftAction: 'Ställ in pass',
  editShiftAction: 'Redigera pass',
  updateShiftTitle: 'Uppdatera pass',
  updateShiftHint: 'Planerade pass kan flyttas mellan stationer och få ny ansvarig, tid och funktionering.',
  updateShiftAction: 'Spara ändringar',
  assignmentsTitle: 'Tilldelningar',
  assignmentsView: 'Tilldelningar',
  personTimelineView: 'Personschema',
  personTimelineTitle: 'Passdeltagares schema',
  personTimelineHint: 'Visar dagens pass för personer som deltar i det valda passet, inklusive ansvarig. Klicka på ett block för att hoppa till det passet.',
  personTimelineResponsibleRole: 'Ansvarig för valt pass',
  personTimelineAssignedRole: 'Tilldelad på valt pass',
  assignmentPersonColumn: 'Person',
  assignmentStatusColumn: 'Status',
  assignmentAssignedColumn: 'Tilldelad',
  assignmentWarningsColumn: 'Varningar',
  noAssignments: 'Inga tilldelningar ännu.',
  noPersonTimeline: 'Inga deltagare att visa schema för.',
  assignPersonTitle: 'Tilldela person',
  assignPersonHint: 'Varningar är beslutsstöd. Koordinatorn kan fortfarande tilldela personen vid behov.',
  assignPersonAction: 'Tilldela person',
  selectCandidateAction: 'Välj',
  applicationCommentLabel: 'Kommentarer och önskemål',
  noApplication: 'Ingen ansökan',
  noWarnings: 'Inga varningar',
  warningCountLabel: 'varningar',
  confirmAssignmentAction: 'Bekräfta tilldelning',
  rejectAssignmentAction: 'Neka tilldelning',
  cancelAssignmentAction: 'Avboka tilldelning',
  missingApplicationWarning: 'Saknar funktionärsansökan.',
  applicationNotApprovedWarning: (status: string) => `Ansökan är ${status}.`,
  stationPreferenceWarning: 'Staffområdet finns inte bland personens önskemål.',
  noAvailabilityWarning: 'Ingen registrerad tillgänglighet finns.',
  unavailableWarning: 'Passet ligger utanför registrerad tillgänglighet.',
  overlapWarning: (count: number) => count === 1
    ? 'Overlappar med ett annat pass.'
    : `Overlappar med ${count} andra pass.`,
  assignmentAlreadyExistsWarning: 'Personen är redan tilldelad passet.',
  plannedOnlyEditHint: 'Bara planerade pass kan uppdateras.',
} as const;
