/** Sidspecifika texter: rubriker, felsidor, tomma tillstånd. */

export const EVENT_DETAIL = {
  backLink:                'Evenemang',
  noName:                  '(Inget namn)',
  rejectTitle:             'Avvisa evenemang',
  rejectHint:              'Ange en kommentar som förklarar varför evenemanget avvisas. Arrangören kan se kommentaren.',
  rejectCommentPlaceholder: 'Beskriv vad som behöver ändras…',
  sendRejection:           'Skicka avvisning',
  pendingCommentsTitle:    'Obehandlade kommentarer',
  responseFieldLabel:      'Beskriv vad som justerats',
  noComments:              'Inga obehandlade kommentarer.',
  detailsTab:              'Detaljer',
  scheduleTab:             'Schema',
  titlePlaceholder:        'Evenemangets titel',
  descriptionPlaceholder:  'Beskriv evenemanget…',
  dropInPlaceholder:       'Beskriv hur drop-in fungerar',
  requestsTitle:           'Sessionönskemål',
  requestsEmpty:           'Inga sessionönskemål.',
  addRequestAction:        'Lägg till sessionönskemål',
  requestDescPlaceholder:  'Kort beskrivning av önskat sessionformat',
  sessionsTitle:           'Schemalagda sessioner',
  sessionsEmpty:           'Inga sessioner schemalagda ännu.',
  addSessionAction:        'Schemalägg session',
  timelineTitle:           'Tidslinje',
  // Bekräftelsedialog – ta bort arrangemang
  deleteTitle:             'Ta bort arrangemang',
  deleteMessage:           (title: string) => `Ta bort arrangemanget "${title}" permanent?`,
} as const;

export const EDITION_DETAIL = {
  backLink:          'Dashboard',
  editTitle:         'Redigera grunddata',
  editTooltip:       'Redigera grunddata',
  lifecycleTab:       'Livscykel',
  stateCardTitle:     'Editionslivscykel',
  stateCardHint:      'Underhåll upplagans livscykel: publicera, aktivera och hantera registreringar.',
  publishTitle:       'Publicering',
  publishHint:        'Upplagan måste publiceras innan den kan aktiveras och öppna registreringar.',
  activeEditionTitle: 'Aktiv upplaga',
  activeEditionHint:  'Den aktiva upplagan används som standard i adminvyer och visas publikt.',
  publicationDone:    'Redan publicerad',
  statusActive:       'Aktiv',
  statusNotActive:    'Inte aktiv',
  registrationsTitle: 'Registreringsfönster',
  registrationsHint:  'Öppna och stäng ansöknings- och registreringsperioder.',
  staffLabel:        'Funktionär:',
  eventLabel:        'Evenemang:',
  publishAction:     'Publicera upplaga',
  unpublishAction:   'Avpublicera upplaga',
  setActiveAction:   'Sätt som aktiv',
  visitorRegLabel:   'Besökarregistrering',
  visitorSubLabel:   'Besökarregistrering:',
  alreadyOpen:       'Redan öppen',
  requiresPublished: 'Kräver publicerad upplaga',
  organiserSubLabel: 'Arrangemangsansökan:',
  staffSubLabel:     'Funktionärsansökan:',
  statusOpen:        'Öppen',
  statusDraft:       'Utkast',
  statusPublished:   'Publicerad',
  statusClosed:      'Stängd',
  venuesTitle:       'Lokaler',
  venuesEmpty:       'Inga lokaler tillagda.',
  addVenueTitle:     'Lägg till lokal',
  staffAreasTitle:   'Funktioneringsområden',
  staffAreasEmpty:   'Inga funktioneringsområden tillagda.',
  addStaffAreaTitle: 'Lägg till funktioneringsområde',
  categoriesTitle:   'Kategorier',
  categoriesEmpty:   'Inga kategorier tillagda.',
  addCategoryTitle:  'Lägg till kategori',
  ticketTypesTitle:  'Biljettyper',
  ticketTypesEmpty:  'Inga biljettyper tillagda.',
  addTicketTitle:    'Lägg till biljetttyp',
  fieldBuilding:          'Byggnad',
  fieldPrice:             'Pris (kr)',
  fieldSellable:          'Säljbar',
  fieldPubliclyVisible:   'Synlig publikt',
  // Bekräftelsedialoger
  publishConfirmTitle:    'Publicera upplaga',
  publishConfirmMessage:  'Publicera upplagan nu?',
  unpublishConfirmTitle:  'Avpublicera upplaga',
  unpublishConfirmMessage:'Avpublicera upplagan och stäng alla registreringsfönster?',
  deleteVenueTitle:       'Ta bort lokal',
  deleteVenueMessage:     (name: string) => `Ta bort lokalen "${name}"?`,
  deleteStaffAreaTitle:   'Ta bort funktioneringsområde',
  deleteStaffAreaMessage: (name: string) => `Ta bort funktioneringsområdet "${name}"? Alla tillhörande stationer tas också bort.`,
  deleteCategoryTitle:    'Ta bort kategori',
  deleteCategoryMessage:  (name: string) => `Ta bort kategorin "${name}"?`,
  deleteTicketTypeTitle:   'Ta bort biljetttyp',
  deleteTicketTypeMessage: (name: string) => `Ta bort biljetttypen "${name}"?`,
} as const;

export const SESSION_TIMELINE = {
  empty:          'Inga sessioner schemalagda ännu. Välj lokal och tid i formuläret för att se ett förslag.',
  conflictBanner: 'Tidskonflikten – den pågående sessionen krockar med en annan session i samma lokal.',
  draftTitle:     'Pågår / förslag',
  conflict:       'Konflikt!',
  inProgress:     'Pågår…',
  legendOwn:      'Eget evenemang',
  legendOther:    'Annat evenemang',
  legendDraft:    'Pågår / förslag',
  legendConflict: 'Konflikt',
} as const;

export const SESSIONS_OVERVIEW = {
  title:            'Schemaläggning',
  formTitle:        'Schemalägg session',
  perspectiveVenue: 'Lokalperspektiv',
  perspectiveEvent: 'Arrangemangsperspektiv',
  buildingFilter:   'Byggnad',
  categoryFilter:   'Kategori',
  searchFilter:     'Fritext',
  allOption:        'Alla',
  requestsForEventTitle: 'Sessionönskemål för valt evenemang',
  noRequestsForEvent: 'Det finns inga registrerade sessionönskemål för evenemanget.',
  timelineView:    'Tidslinjevy',
  tableView:       'Tabellvy',
  timelineTitleVenue: 'Tidslinje per lokal',
  timelineTitleEvent: 'Tidslinje per arrangemang',
  scheduledTitle:   'Schemalagda sessioner',
  noSessions:       'Inga schemalagda sessioner i aktuellt urval.',
  conflictDetected: 'Konflikt upptäckt: sessionen överlappar annan session i samma lokal.',
  updateSession:    'Uppdatera session',
  deleteSessionTitle: 'Ta bort session',
  deleteSessionMessage: 'Vill du ta bort sessionen? Den inaktiveras och visas inte längre i schemat.',
  eventColumn:      'Evenemang',
  start:            'Start',
  end:              'Slut',
} as const;

export const ERROR_PAGE = {
  '401': {
    code:        '401',
    title:       'Inte inloggad',
    description: 'Du måste logga in för att komma åt den här sidan.',
    action:      'Gå till inloggning',
  },
  '403': {
    code:        '403',
    title:       'Ingen behörighet',
    description: 'Du har inte behörighet att se den här sidan. Adminrättigheter krävs.',
    action:      'Till inloggning',
  },
  '404': {
    code:        '404',
    title:       'Sidan hittades inte',
    description: 'Sidan du letar efter finns inte eller har flyttats.',
    action:      'Tillbaka till start',
  },
} as const;
